name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "ESTE ES EL PASO DE CONSTRUCCION"

  test:
    runs-on: ubuntu-latest
    needs: build
      
    steps: 
      - name: Paso de testeo
        run: echo "este es el paso de testeo" 
  deploy:
    runs-on: ubuntu-last
    needs: test

    steps:
      - name: paso de despliege
        run: echo "este es el paso de despliege"


